name: Docker Workflow
on:
  push
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update token
        run: |
          sed -i "s/<TOKEN>/${TELEGRAM_API_TOKEN}/g" tgbot/config.py
        shell: bash
        env:
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/domopoisk:1.0.1
          
